import { ICON_COMPLETE_PATH, LOGO_IMAGE_PATH, TARMAC_STATIC_URL } from 'src/utils/urlAPIs';

export const ADD_INFO_SAVE_ICON = `${ICON_COMPLETE_PATH}save%402x.png`;
export const APP_STORE_ICON = `${TARMAC_STATIC_URL}${LOGO_IMAGE_PATH}APP_STORE_LOGO.png`;
export const BACK_ICON = `${ICON_COMPLETE_PATH}BACK_ICON_WHITE.png`;
export const CARRIER_LOGO_PATH = `${TARMAC_STATIC_URL}/img/airlines/`;
export const CLOSE_ICON = `${ICON_COMPLETE_PATH}CLOSED_CROSS.png`;
export const COMMENT_ICON = `${ICON_COMPLETE_PATH}COMMENT_WHITE.png`;
export const LANDING_PLANE_WHITE_ICON = `${ICON_COMPLETE_PATH}LANDING_PLANE_ICON_WHITE.png`;
export const LOGOUT_IMAGE_URL = `${ICON_COMPLETE_PATH}logout.png`;
export const MESSAGE_ICON = `${ICON_COMPLETE_PATH}MESSAGE_WHITE.png`;
export const PLAY_STORE_ICON = `${TARMAC_STATIC_URL}${LOGO_IMAGE_PATH}PLAY_STORE_LOGO.png`;
export const TAKEOFF_WHITE_ICON = `${ICON_COMPLETE_PATH}TAKEOFF_PLANE_ICON_WHITE.png`;
export const TARMAC_LOGO_IMAGE_URL = `${TARMAC_STATIC_URL}/img/Logo-White.png`;
