# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AGOA Test and Build

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.17.0
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.0
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: 'Etc/GMT+3'  
    - name: Install npm and run test
      run: |
          npm --version
          npm install
          npm run test
